
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: post_exam_development

test:
  <<: *default
  database: post_exam_test

production:
  <<: *default
  database: post_exam_production
  username: post_exam
  password: <%= ENV['POST_EXAM_DATABASE_PASSWORD'] %>
